on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          run_install: true

      - name: Build project
        run: pnpm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "f9b287db44d75988c9ac726f6390d9c0"
          projectName: "tuhura-tech-website"
          directory: dist/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
